FROM python:3.12-slim

WORKDIR /app

# Copia de requerimientos
COPY requirements.txt .

# Instalación sin guiones extra
RUN pip install --no-cache-dir -r requirements.txt

# Copia la carpeta de código
COPY ./app ./app

EXPOSE 5000

# El comando busca dentro de la carpeta app el archivo main.py
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]